# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  CI: '1'

strategy:
  matrix:
    Linux:
      ImageName: 'ubuntu-latest'
    Macintosh:
      ImageName: 'macos-latest'
    Windows:
      ImageName: 'windows-latest'

pool:
  vmImage: $(ImageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install NPM and build'

- script: npm test
  displayName: 'Run tests'