
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    steps:
      - checkout

      - restore_cache:
          keys:
          - node_modules-cache-{{ checksum "package.json" }}
          - node_modules-cache-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: node_modules-cache-{{ checksum "package.json" }}

      # - run:
      #     name: Lint codebase
      #     command: |
      #       npm run lint

      # - run:
      #     name: Unit tests
      #     command: |
      #       npm run test

      - run:
          name: Build React app
          command: |
            CI=false npm run ui:build

      - run:
          name: Package app
          command: |
            mkdir dist
            tar czf ./dist/octopus-web-app_$(echo $CIRCLE_BUILD_NUM).tar.gz package.json build server node_modules

      - store_artifacts:
          path: ./dist
